config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users do
    resources :tweets
    resources :follows, only: [:create]
    delete :unfollow, to: "follows#unfollow"
  end

  root to: "pages#home"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :content, length: { maximum: 160 }
  validates :content, presence: true
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  def show
    user_id = params[:user_id]
    user = User.find(user_id)

    @tweet = user.tweets.find(params[:id])

  end

  def index
    user_id = params[:user_id]
    user = User.find(user_id)

    # Get request
    @tweets = user.tweets.all

    respond_to do |format|
      format.html
      format.json { render json: @tweets }
    end
  end

  def new
    # Get request
    @tweet = current_user.tweets.new
  end

  def create
    # Post request
    @tweet = current_user.tweets.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to user_tweet_path(current_user, @tweet) }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def destroy
    @tweet = current_user.tweets.find(params[:id])

    if @tweet.destroy
      redirect_to user_tweets_path(current_user)
    end
  end

  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  def update
    @tweet = current_user.tweets.find(params[:id])

    if @tweet.update(tweet_params)
      redirect_to user_tweets_path(current_user)
    end
  end

  protected
  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<p>Errors:</p>
<ul>
  <%- tweet.errors.full_messages.each do |error| %>
    <li>
      <%= error %>
    </li>
  <% end %>
</ul>

<%= form_for tweet, url: user_tweets_path do |f| %>
  <%= f.text_area(:content) %>
  <%= f.submit %>
<%- end %>

app/views/tweets/_single_tweet.html.erb
<div id="tweet">
  <p> ID: <%= tweet_var.id %> </p>
  <p> Content: <%= tweet_var.content %> </p>
  <p> <%= link_to "Delete!", user_tweet_path(tweet_var.user, tweet_var.id), :method => "delete", :data => {:confirm => "Are you sure you want to delete?"}%> </p>
  <p> <%= link_to "Edit!", edit_user_tweet_path(tweet_var.user, tweet_var.id) %> </p>
  <p> <%= link_to "Details", user_tweet_path(tweet_var.user, tweet_var.id) %> </p>  
  <hr>
</div>

app/views/tweets/create.js.erb
<%- if !@tweet.errors.present? %>
  $("#errors").html('');
  var tweets = $("#tweets-div");

  tweets.prepend("<%= escape_javascript(render('single_tweet', tweet_var: @tweet)) %>");

  $("#tweet-content-text").val('');
<%- else %>
  $("#errors").html("<%= escape_javascript(@tweet.errors.full_messages.join('<br>')) %>");
<%- end %>

app/views/tweets/edit.html.erb
Edit page:

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
Index page:
This will display all the tweets

<% @tweets.each do |tweet| %>
  <%= render "single_tweet", tweet_var: tweet %>
<% end %>

app/views/tweets/new.html.erb
New page:

<%= render "form", tweet: @tweet %>

app/views/tweets/show.html.erb
Show Page

<%= render "single_tweet", tweet_var: @tweet %>