config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users do
    resources :tweets
    resources :follows, only: [:create]
    delete :unfollow, to: "follows#unfollow"
  end

  root to: "pages#home"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets, :dependent => :destroy

  has_many :follows, foreign_key: "follower_id"
  has_many :followers, class_name: "User", through: :follows, foreign_key: "following_id"
  has_many :followings, class_name: "User", through: :follows, foreign_key: "follower_id"

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates :email, :first_name, :last_name, presence: true
  validates :email, :format => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validate :first_name_must_be_upcase
  # validate :must_have_at_least_one_tweet

  # Custom validations
  def first_name_must_be_upcase
    fn = first_name.first

    unless /[[:upper:]]/.match(fn)
      errors.add(:first_name, "must be capitalized")
    end
  end

  def must_have_at_least_one_tweet
    if tweets.count == 0
      errors.add(:base, "must have at least one tweet.")
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]


  def index
    @users = User.all

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  protected

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :avatar)
  end
end

app/views/users/_single_user.html.erb
<p>
  <%= user.first_name %>
  <%= user.last_name %>
  <%= user.email %>

  <%= link_to "Profile", user_path(user) %>
</p>

app/views/users/edit.html.erb
<%= form_for current_user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br>

  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>

  <%= f.label :avatar %>
  <%= image_tag current_user.avatar.url(:medium) %>

  <%= f.file_field :avatar %>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= render "single_user", user: user %>
<% end %>

app/views/users/show.html.erb
<%- flash.each do |key, value| %>
  <ul>
    <li><%= value %></li>
  </ul>
<%- end %>

This is the user's profile:

<div class="">
  <%- if current_user != @user && user_signed_in? && !current_user.followings.include?(@user) %>
    <%= link_to "Follow this user!", user_follows_path(@user), method: :post, class: "btn btn-primary" %> 
  <% end %>

  <%- if user_signed_in? && current_user.followings.include?(@user) %>
    <%= link_to "Unfollow", user_unfollow_path(@user), method: :delete, class: "btn btn-danger" %>
  <% end %>
</div>

<br>

<div class="">
  <%= image_tag @user.avatar.url(:thumb) %>
</div>

<div><%= @user.first_name %></div>
<br>
<%= @user.last_name %>
<br>
<%= @user.email %>


<h3>Tweets</h3>

<%- if user_signed_in? %>
  <%= form_for current_user.tweets.new, url: user_tweets_path(current_user), remote: true do |f| %>
    <div id="errors"></div>

    <%= f.text_field :content, id: "tweet-content-text" %>
    <%= f.submit %>
  <% end %>
<% end %>

<div id="tweets-div">
  <%- @user.tweets.order(created_at: :desc).each do |tweet| %>
    <%= render "tweets/single_tweet", tweet_var: tweet %>
  <%- end %>
</div>